In [1]:
import pandas as pd
import numpy as np

In [2]:
df_1 = pd.read_csv('All row files/1. US Police Shootings/shootings.csv',index_col=False)

In [3]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4895 entries, 0 to 4894
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       4895 non-null   int64
 1   name                     4895 non-null   object
 2   date                     4895 non-null   object
 3   manner_of_death          4895 non-null   object
 4   armed                    4895 non-null   object
 5   age                      4895 non-null   float64
 6   gender                   4895 non-null   object
 7   race                     4895 non-null   object
 8   city                     4895 non-null   object
 9   state                    4895 non-null   object
 10  signs_of_mental_illness  4895 non-null   bool
 11  threat_level             4895 non-null   object
 12  flee                     4895 non-null   object
 13  body_camera              4895 non-null   bool
 14  arms_category            4895 non-null   object
dtypes: bool(2), float64(1), int64(1), object(11)
memory usage: 506.8+ KB

In [4]:
df_1['id'].duplicated().sum()

0

In [5]:
df_1['manner_of_death'].unique()

array(['shot', 'shot and Tasered'], dtype=object)

In [6]:
df_1['armed'].unique()

array(['gun', 'unarmed', 'toy weapon', 'nail gun', 'knife', 'unknown',
       'shovel', 'hammer', 'hatchet', 'sword', 'machete', 'box cutter',
       'metal object', 'screwdriver', 'lawn mower blade', 'flagpole',
       'guns and explosives', 'cordless drill', 'metal pole', 'Taser',
       'metal pipe', 'metal hand tool', 'blunt object', 'metal stick',
       'sharp object', 'meat cleaver', 'carjack', 'chain',
       "contractor's level", 'stapler', 'crossbow', 'bean-bag gun',
       'baseball bat and fireplace poker', 'straight edge razor',
       'gun and knife', 'ax', 'brick', 'baseball bat', 'hand torch',
       'chain saw', 'garden tool', 'scissors', 'pole', 'pick-axe',
       'flashlight', 'vehicle', 'spear', 'chair', 'pitchfork',
       'hatchet and gun', 'rock', 'piece of wood', 'bayonet', 'pipe',
       'glass shard', 'motorcycle', 'pepper spray', 'metal rake', 'baton',
       'crowbar', 'oar', 'machete and gun', 'air conditioner',
       'pole and knife', 'beer bottle', 'baseball bat and bottle',
       'fireworks', 'pen', 'chainsaw', 'gun and sword', 'gun and car',
       'pellet gun', 'BB gun', 'incendiary device', 'samurai sword',
       'bow and arrow', 'gun and vehicle', 'vehicle and gun', 'wrench',
       'walking stick', 'barstool', 'grenade', 'BB gun and vehicle',
       'wasp spray', 'air pistol', 'baseball bat and knife',
       'vehicle and machete', 'ice pick', 'car, knife and mace'],
      dtype=object)

In [7]:
df_1['gender'].unique()

array(['M', 'F'], dtype=object)

In [8]:
df_1['race'].unique()

array(['Asian', 'White', 'Hispanic', 'Black', 'Other', 'Native'],
      dtype=object)

In [9]:
df_1['state'].unique()

array(['WA', 'OR', 'KS', 'CA', 'CO', 'OK', 'AZ', 'IA', 'PA', 'TX', 'OH',
       'LA', 'MT', 'UT', 'AR', 'IL', 'NV', 'NM', 'MN', 'MO', 'VA', 'NJ',
       'IN', 'KY', 'MA', 'NH', 'FL', 'ID', 'MD', 'NE', 'MI', 'GA', 'TN',
       'NC', 'AK', 'NY', 'ME', 'AL', 'MS', 'WI', 'SC', 'DE', 'DC', 'WV',
       'HI', 'WY', 'ND', 'CT', 'SD', 'VT', 'RI'], dtype=object)

In [10]:
df_1['arms_category'].unique()

array(['Guns', 'Unarmed', 'Other unusual objects', 'Piercing objects',
       'Sharp objects', 'Unknown', 'Blunt instruments', 'Multiple',
       'Electrical devices', 'Hand tools', 'Vehicles', 'Explosives'],
      dtype=object)

###  Cargar csv profile killers üîç

In [11]:
df_2 = pd.read_csv('All row files/2. Wikipedia Serial Killers List/profile_killers.csv')

In [12]:
df_2.head()

,Name,Nicknames,Age,Born Date,Born Location,Died Date,Died Location,Conviction,Criminal Penalty,Date Apprehended
0,Luis Garavito,"The Beast, Goofy, Conflict, Bonifacio Morera L...",66.0,1957-01-25,"Gnova, Quindo, Colombia",2023-10-12,"Valledupar, Colombia",NaN,NaN,1999-04-22
1,Pedro L√≥pez,The Monster of the Andes,NaN,1948-10-08,"Venadillo, Colombia",NaN,NaN,"Vehicle Theft, Murder, Rape","7 years imprisonment in Colombia, extended to ...",1980-03-09
2,Javed Iqbal,Kukri,NaN,NaN,"Lahore, Punjab, Pakistan",NaN,"Lahore, Punjab, Pakistan","Child Se Abuse, Murder",death,1999-12-30
3,Mikhail Popkov,"The Werewolf, The Angarsk Maniac, The Wednesda...",NaN,1964-03-07,"Norilsk, Krasnoyarsk Krai, Russian SFSR, USSR",NaN,NaN,Aggravated Murder Attempted Aggravated Murder,life imprisonment,2012-06-23
4,Daniel Camargo Barbosa,"The Sadist of El Charquito, The Monster of the...",64.0,1930-01-22,"Anolaima, Cundinamarca, Colombia",1994-11-13,"Guayaquil, Ecuador",NaN,"25 years imprisonment, 16 years imprisonment",1974-05-03

In [13]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 711 entries, 0 to 710
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              711 non-null    object
 1   Nicknames         469 non-null    object
 2   Age               243 non-null    float64
 3   Born Date         444 non-null    object
 4   Born Location     420 non-null    object
 5   Died Date         308 non-null    object
 6   Died Location     227 non-null    object
 7   Conviction        502 non-null    object
 8   Criminal Penalty  577 non-null    object
 9   Date Apprehended  543 non-null    object
dtypes: float64(1), object(9)
memory usage: 55.7+ KB

### Crear columna Born country con solo el pa√≠s de nacimiento üåÜ

In [14]:
df_2['born country'] = df_2['Born Location'].apply(
    lambda x: x.split(',')[-1].strip() if pd.notnull(x) else None
)

In [15]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 711 entries, 0 to 710
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              711 non-null    object
 1   Nicknames         469 non-null    object
 2   Age               243 non-null    float64
 3   Born Date         444 non-null    object
 4   Born Location     420 non-null    object
 5   Died Date         308 non-null    object
 6   Died Location     227 non-null    object
 7   Conviction        502 non-null    object
 8   Criminal Penalty  577 non-null    object
 9   Date Apprehended  543 non-null    object
 10  born country      420 non-null    object
dtypes: float64(1), object(10)
memory usage: 61.2+ KB

### Guardar el df_2 en archivo csv üìÇ

In [24]:
df_2.to_csv('V1-profile_killers.csv', index=False)

### Cargar archivo Serial killers by victims üí°

In [7]:
df_2_a = (pd.read_csv('All row files/2. Wikipedia Serial Killers List/serial_killers_by_victims.csv'))

In [8]:
df_2_a.head(10)

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,country sorted,Continent
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992.0,1999.0,193.0,247.0,"Child-murderer, torture-killer, and rapist kno...",Multiple Countries,Multiple
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969.0,1980.0,110.0,300.0,"Child-murderer and rapist, known as ""The Monst...",Multiple Countries,South America
2,Javed Iqbal,Pakistan,1998.0,1999.0,100.0,100.0,"Child-murderer and rapist, known as ""Kukri"", I...",Pakistan,Asia
3,Mikhail Popkov,Russia,1992.0,2010.0,83.0,86.0,"Serial rapist-killer nicknamed ""The Werewolf"",...",Russia,Europe/Asia
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974.0,1986.0,72.0,180.0,"Child and woman murderer, believed to have pos...",Multiple Countries,Multiple
5,Pedro Rodrigues Filho,Brazil,1967.0,2003.0,71.0,100.0,Rodrigues Filho claimed to have killed over 10...,Brazil,South America
6,Kampatimar Shankariya,India,1977.0,1978.0,70.0,70.0,Shankariya was an Indian serial killer who use...,India,Asia
7,Hoshang Amini,Iran,1954.0,1962.0,67.0,67.0,"Known as the ""Ghost of the Qanat Wells"". Murde...",Iran,Asia
8,Yang Xinhai,China,1999.0,2003.0,67.0,67.0,"Known as the ""Monster Killer"". Yang would ente...",China,Asia
9,Abul Djabar,Afghanistan,NaN,1970.0,65.0,300.0,Killed 65 men and boys by strangling them with...,Afghanistan,Asia

In [9]:
df_2_a["Country"].unique()

array(['Colombia, Ecuador, Venezuela', 'Colombia, Peru, Ecuador',
       'Pakistan', 'Russia', 'Colombia, Ecuador, Brazil', 'Brazil',
       'India', 'Iran', 'China', 'Afghanistan', 'United States',
       'Belgian Congo, Tanganyika', 'Soviet Union',
       'Soviet Union, Ukraine', 'Indonesia', 'South Africa', 'Morocco',
       'Kingdom of Romania, Yugoslavia, Hungary', 'Mexico',
       'Ottoman Empire, Iraq, Iran', 'Egypt', 'Germany', 'Colombia',
       'Zambia', 'Swaziland', 'Greece', 'Canada', 'United Kingdom',
       'Austria-Hungary', 'France, Germany, Switzerland', 'Ecuador',
       'United States, Canada', 'Soviet Union, Russia, Tajikistan',
       'Romania', 'South Korea', 'Costa Rica', 'Soviet Union, Russia',
       'Latvia', 'Turkey', 'France', 'Sri Lanka', 'Peru', 'Ukraine',
       'Italy', 'France, Belgium', 'Spain', 'United States, Mexico',
       'Argentina', 'Poland', 'Chile', 'West Germany', 'Tunisia',
       'Venezuela', 'Rwanda', 'Thailand, Nepal, India, Malaysia', 'Yemen',
       'Japan', 'Austria, United States, Czechoslovakia', 'Belgium',
       'Bangladesh', 'Czechoslovakia', 'Soviet Union, Russia, Ukraine',
       'Kenya', 'German Empire, Germany', 'Denmark', 'Ecuador, Spain',
       'Czechoslovakia, Germany, Netherlands', 'Sweden', 'China, Japan',
       'Australia', 'Spain, France, Italy', 'Canada, United States',
       'Cyprus', 'Italy, France',
       'East Germany, Germany, France, Spain, Czech Republic, Italy',
       'Belarus', 'East Germany, Germany', 'Estonia',
       'United States, Portuguese Angola',
       'Switzerland, France, United States, Yugoslavia, Italy',
       'West Germany, United States', 'Netherlands', 'SR Croatia',
       'Panama', 'Singapore', 'Belize', 'SR Slovenia', 'Namibia',
       'United Kingdom, Ireland, West Germany, Netherlands, France',
       'Austria', 'Hong Kong', 'Israel',
       'Allied-occupied Germany, West Germany', 'Republic of Macedonia',
       'East Germany', 'SR Slovenia, Serbia and Montenegro, Slovenia',
       'Portugal', 'Malaysia',
       'United States, Austria, France, United Kingdom',
       'Singapore, Malaysia', 'Kingdom of Yugoslavia', 'Iraq', 'Norway',
       'Switzerland', 'Czech Republic', 'Imperial State of Iran',
       'Finland', 'United States, Zimbabwe', 'Hungary', 'Belgium, France',
       'Guatemala', 'Uzbekistan, Kazakhstan',
       'Italy, West Germany, Netherlands'], dtype=object)

In [10]:
df_2_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 757 entries, 0 to 756
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              757 non-null    object
 1   Country           757 non-null    object
 2   Start year        738 non-null    float64
 3   End year          740 non-null    float64
 4   Proven victims    757 non-null    float64
 5   Possible victims  757 non-null    float64
 6   Notes             754 non-null    object
 7   country sorted    757 non-null    object
 8   Continent         756 non-null    object
dtypes: float64(4), object(5)
memory usage: 53.4+ KB

In [17]:
df_2["born country"].unique()

array(['Colombia', 'Pakistan', 'USSR', 'Brazil', 'India', 'Iran', 'China',
       'Abul DjabarAfghanistan', None, 'Protectorate of Uganda',
       'Soviet Union', 'Indonesia', 'South Africa', 'Byelorussian SSR',
       'Morocco', 'Romania', 'Mexico', 'Russian Empire', 'Egypt',
       'Greece', 'Maoupa Cedric MaakeSouth Africa', 'Canada', 'England',
       'German Empire', 'Hungary', 'France', 'Ecuador', 'RSFSR',
       'South Korea', 'Turkey', 'United States', 'Martinique', 'Peru',
       'Ukrainian SSR', 'Italy', 'Imperial State of Iran', 'Spain',
       'Elias XitavhudziUnion of South Africa', 'Uttar Pradesh',
       'Argentina', 'Union of South Africa', 'Norway', 'Poland', 'Chile',
       'Germany', 'French Tunisia', 'United States of Brazil',
       'Venezuela', 'Tajik SSR', 'Latvia',
       'Johannes MashianeSouth Africa', 'Georgian SSR',
       'North German Confederation', 'Scotland', 'Yemen',
       'occupied Austria', 'Belgium', 'Japan', 'So Paulo', 'Latvian SSR',
       'UkSSR', 'Zhejiang', 'Kenya', 'Denmark', 'Texas', 'Czechoslovakia',
       'Occupied Japan', 'Australia', 'Sweden', 'Empire of Japan', 'UK',
       'Imperial Germany', 'Ontario Canada', 'Chongqing', 'East Germany',
       'BSSR', 'Costa Rica', 'West Germany', 'Nigeria', 'Switzerland',
       'Kingdom of Yugoslavia', 'German Confederation', 'Netherlands',
       'Israel', 's Republic', 'Yugoslavia', 'Wales', 'Massachusetts',
       'Slovakia', 'unknown', 'Nazi Germany', 'British Hong Kong',
       'occupied Germany', 'Kingdom of Romania', 'Moldavian SSR', 's',
       'FukuokaOccupied Japan', 'SFR Yugoslavia', 'Congress Poland',
       'Cape Colony', 'Canary Islands',
       'Socialist Federal Republic of Yugoslavia',
       'Gabriel Garza HothMexico', 'United Kingdom', 'Hong Kong',
       'Portugal', 'sMexico', 'US', 'New York', 'Malaysia',
       'Grand Duchy of Hesse', 'Kingdom of Prussia', 'Singapore',
       'TaeiIraq', 'Westphalia', 'Austria', 'Czech Republic', 'Ireland',
       'centuryOttoman Empire', 'Rio de Janeiro', 'Guatemala',
       'Uzbek SSR', 'Mxico', 'Russia', 'Territory of Hawaii'],
      dtype=object)

In [23]:
country_to_continent = {
    # Am√©ricas
    "Brazil": "South America",
    "Colombia": "South America",
    "Argentina": "South America",
    "Chile": "South America",
    "Ecuador": "South America",
    "Peru": "South America",
    "Mexico": "North America",
    "United States": "North America",
    "Canada": "North America",
    "Costa Rica": "Central America",
    "Guatemala": "Central America",
    "Belize": "Central America",
    "Panama": "Central America",
    # Europa
    "France": "Europe",
    "Germany": "Europe",
    "Spain": "Europe",
    "Italy": "Europe",
    "United Kingdom": "Europe",
    "Poland": "Europe",
    "Romania": "Europe",
    "Hungary": "Europe",
    "Ukraine": "Europe",
    "Russia": "Europe/Asia",  # pode ser refinado
    "Austria": "Europe",
    "Czech Republic": "Europe",
    "Netherlands": "Europe",
    "Switzerland": "Europe",
    "Belgium": "Europe",
    "Latvia": "Europe",
    "Greece": "Europe",
    "Serbia and Montenegro": "Europe",
    "Estonia": "Europe",
    "Republic of Macedonia": "Europe",
    # √Åsia
    "China": "Asia",
    "India": "Asia",
    "Pakistan": "Asia",
    "Iran": "Asia",
    "Afghanistan": "Asia",
    "Indonesia": "Asia",
    "South Korea": "Asia",
    "North Korea": "Asia",
    "Japan": "Asia",
    "Bangladesh": "Asia",
    "Turkey": "Asia/Europe",
    "Kazakhstan": "Asia",
    "Tajikistan": "Asia",
    "Sri Lanka": "Asia",
    "Malaysia": "Asia",
    "Thailand": "Asia",
    "Nepal": "Asia",
    "Uzbekistan": "Asia",
    "Yemen": "Asia",
    "Israel": "Asia",
    # √Åfrica
    "South Africa": "Africa",
    "Egypt": "Africa",
    "Morocco": "Africa",
    "Zambia": "Africa",
    "Swaziland": "Africa",
    "Rwanda": "Africa",
    "Namibia": "Africa",
    "Portuguese Angola": "Africa",
    "Tanganyika": "Africa",
    "Belgian Congo": "Africa",
    "Kenya": "Africa",
    # Oceania
    "Australia": "Oceania",
    "New Zealand": "Oceania",
    # Outros
    "Soviet Union": "Former USSR",
    "Ottoman Empire": "Historical",
    "Austria-Hungary": "Historical",
    "Czechoslovakia": "Historical",
    "West Germany": "Historical",
    "East Germany": "Historical",
    "SR Croatia": "Historical",
    "SR Slovenia": "Historical",
    "Kingdom of Romania": "Historical",
    "Kingdom of Yugoslavia": "Historical",
}

In [ ]:
# Exemplo com lista
countries = ['Colombia, Ecuador, Venezuela', 'Pakistan', 'Russia']
df = pd.DataFrame({'countries': countries})
# Aplica categoriza√ß√£o
df['continents'], not_matched = categorize_by_continent(df['countries'], country_to_continent)
print(df)
print("Not matched countries:", not_matched)

In [40]:
def categorize_multiple_countries(country_series):
    return country_series.apply(lambda x: "Multiple Countries" if ',' in x else x)

In [44]:
df_2_country_sorted = pd.DataFrame({'Country': df_2_a["Country"]})

# Aplica a fun√ß√£o
df_2_a['country sorted'] = categorize_multiple_countries(df_2_a['Country'])

display(df_2_a)

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,country sorted
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992.0,1999.0,193.0,247.0,"Child-murderer, torture-killer, and rapist kno...",Multiple Countries
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969.0,1980.0,110.0,300.0,"Child-murderer and rapist, known as ""The Monst...",Multiple Countries
2,Javed Iqbal,Pakistan,1998.0,1999.0,100.0,100.0,"Child-murderer and rapist, known as ""Kukri"", I...",Pakistan
3,Mikhail Popkov,Russia,1992.0,2010.0,83.0,86.0,"Serial rapist-killer nicknamed ""The Werewolf"",...",Russia
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974.0,1986.0,72.0,180.0,"Child and woman murderer, believed to have pos...",Multiple Countries
...,...,...,...,...,...,...,...,...
752,Michael Bear Carson and Suzan Carson,United States,1981.0,1983.0,3.0,3.0,Nomadic hippie killers involved in the counter...,United States
753,Joseph and Michael Kallinger,United States,1974.0,1975.0,3.0,3.0,Joseph Kallinger murdered three people and tor...,United States
754,Silvia Merez Cult,Mexico,2009.0,2012.0,3.0,3.0,Ritually murdered three people in sacrifices t...,Mexico
755,Raya and Sakina and their husbands,Egypt,1919.0,1920.0,2.0,2.0,Gang of four that rented a house for women and...,Egypt
756,Amelia Sach and Annie Walters,United Kingdom,1900.0,1903.0,1.0,300.0,"Sach and Walters, known as the ""Finchley baby ...",United Kingdom

In [53]:
df_2_a[df_2_a["country sorted"]=="Multiple Countries"].shape[0]

44

In [56]:
continent_dict = {
    'Multiple Countries': 'Multiple',
    'Pakistan': 'Asia',
    'Russia': 'Europe/Asia',
    'Brazil': 'South America',
    'India': 'Asia',
    'Iran': 'Asia',
    'China': 'Asia',
    'Afghanistan': 'Asia',
    'United States': 'North America',
    'Soviet Union': 'Europe/Asia',
    'Indonesia': 'Asia',
    'South Africa': 'Africa',
    'Morocco': 'Africa',
    'Mexico': 'North America',
    'Egypt': 'Africa',
    'Germany': 'Europe',
    'Colombia': 'South America',
    'Zambia': 'Africa',
    'Swaziland': 'Africa',
    'Greece': 'Europe',
    'Canada': 'North America',
    'United Kingdom': 'Europe',
    'Austria-Hungary': 'Europe',
    'Ecuador': 'South America',
    'Romania': 'Europe',
    'South Korea': 'Asia',
    'Costa Rica': 'North America',
    'Latvia': 'Europe',
    'Turkey': 'Europe/Asia',
    'France': 'Europe',
    'Sri Lanka': 'Asia',
    'Peru': 'South America',
    'Ukraine': 'Europe',
    'Italy': 'Europe',
    'Spain': 'Europe',
    'Argentina': 'South America',
    'Poland': 'Europe',
    'Chile': 'South America',
    'West Germany': 'Europe',
    'Tunisia': 'Africa',
    'Venezuela': 'South America',
    'Rwanda': 'Africa',
    'Yemen': 'Asia',
    'Japan': 'Asia',
    'Belgium': 'Europe',
    'Bangladesh': 'Asia',
    'Czechoslovakia': 'Europe',
    'Kenya': 'Africa',
    'Denmark': 'Europe',
    'Sweden': 'Europe',
    'Australia': 'Oceania',
    'Cyprus': 'Asia',
    'Belarus': 'Europe',
    'Estonia': 'Europe',
    'Netherlands': 'Europe',
    'SR Croatia': 'Europe',
    'Panama': 'North America',
    'Singapore': 'Asia',
    'Belize': 'North America',
    'SR Slovenia': 'Europe',
    'Namibia': 'Africa',
    'Austria': 'Europe',
    'Hong Kong': 'Asia',
    'Israel': 'Asia',
    'Republic of Macedonia': 'Europe',
    'East Germany': 'Europe',
    'Portugal': 'Europe',
    'Malaysia': 'Asia',
    'Kingdom of Yugoslavia': 'Europe',
    'Iraq': 'Asia',
    'Norway': 'Europe',
    'Switzerland': 'Europe',
    'Czech Republic': 'Europe',
    'Imperial State of Iran': 'Asia',
    'Finland': 'Europe',
    'Hungary': 'Europe',
    'Guatemala': 'North America'
}


df_2_a['Continent'] = df_2_a['country sorted'].map(continent_dict)

In [63]:
df_2_a.head()

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,country sorted,Continent
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992,1999,193,247,"Child-murderer, torture-killer, and rapist kno...",Multiple Countries,Multiple
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969,1980,110,300,"Child-murderer and rapist, known as ""The Monst...",Multiple Countries,Multiple
2,Javed Iqbal,Pakistan,1998,1999,100,100,"Child-murderer and rapist, known as ""Kukri"", I...",Pakistan,Asia
3,Mikhail Popkov,Russia,1992,2010,83,86,"Serial rapist-killer nicknamed ""The Werewolf"",...",Russia,Europe/Asia
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974,1986,72,180,"Child and woman murderer, believed to have pos...",Multiple Countries,Multiple

In [58]:
df_2_a["Continent"].unique()

array(['Multiple', 'Asia', 'Europe/Asia', 'South America',
       'North America', 'Africa', 'Europe', 'Oceania'], dtype=object)

In [59]:
df_2_a.to_csv("All row files/2. Wikipedia Serial Killers List/serial_killers_by_victims.csv", index=False)

In [60]:
columnas=["Start year","End year", "Proven victims","Possible victims"]

In [61]:
for col in columnas:
    df_2_a[col] = df_2_a[col].round().astype('Int64')

In [62]:
df_2_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 757 entries, 0 to 756
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              757 non-null    object
 1   Country           757 non-null    object
 2   Start year        738 non-null    Int64
 3   End year          740 non-null    Int64
 4   Proven victims    757 non-null    Int64
 5   Possible victims  757 non-null    Int64
 6   Notes             754 non-null    object
 7   country sorted    757 non-null    object
 8   Continent         757 non-null    object
dtypes: Int64(4), object(5)
memory usage: 56.3+ KB

In [2]:
df_killers_byvictims = (pd.read_csv('All row files/2. Wikipedia Serial Killers List/V1-serial_killers_by_victims.csv'))

In [3]:
df_killers_byvictims.head()

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,Continent,Country Sorted
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992.0,1999.0,193,247,"Child-murderer, torture-killer, and rapist kno...",South America,Multiple Countries
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969.0,1980.0,110,300,"Child-murderer and rapist, known as ""The Monst...",South America,Multiple Countries
2,Javed Iqbal,Pakistan,1998.0,1999.0,100,100,"Child-murderer and rapist, known as ""Kukri"", I...",Asia,Pakistan
3,Mikhail Popkov,Russia,1992.0,2010.0,83,86,"Serial rapist-killer nicknamed ""The Werewolf"",...",Europe,Russia
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974.0,1986.0,72,180,"Child and woman murderer, believed to have pos...",South America,Multiple Countries

In [4]:
columnas=["Start year","End year","Years Active"]

In [ ]:
for col in columnas:
df_killers_byvictims[col] = df_killers_byvictims[col].round().astype('Int64')

KeyError: 'Years Active'

In [73]:
df_killers_byvictims.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 757 entries, 0 to 756
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              757 non-null    object
 1   Country           757 non-null    object
 2   Start year        738 non-null    Int64
 3   End year          740 non-null    Int64
 4   Proven victims    757 non-null    int64
 5   Possible victims  757 non-null    int64
 6   Notes             754 non-null    object
 7   Continent         757 non-null    object
 8   Country Sorted    757 non-null    object
 9   Years Active      723 non-null    Int64
 10  Decade            757 non-null    object
 11  Crime Type        757 non-null    object
 12  GroupType         757 non-null    object
 13  Killer Type       757 non-null    object
dtypes: Int64(3), int64(2), object(9)
memory usage: 85.1+ KB

### üî™Crear Top 10 de Serial Killers mundiales con columna de imagenes

In [28]:
# Ordenar por v√≠ctimas confirmadas y quedarnos con los 15 primeros
top15 = df_killers_byvictims.sort_values(by='Possible victims', ascending=False,).head(15).copy()
top15

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,Continent,Country Sorted,Killer Type,Decade
675,Murder Incorporated,United States,1920,<NA>,400,1000,Murder Incorporated or Murder Inc. for short w...,North America,United States,Gang,1920s
737,The Skin Hunters,Poland,<NA>,2002,5,620,Hospital crew that killed patients in order to...,Europe,Poland,Gang,<NA>s
631,Charles Cullen,United States,1988,2003,29,400,Nurse in New Jersey and Pennsylvania who murde...,North America,United States,Male,1980s
756,Amelia Sach and Annie Walters,United Kingdom,1900,1903,1,300,"Sach and Walters, known as the ""Finchley baby ...",Europe,United Kingdom,Female,1900s
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969,1980,110,300,"Child-murderer and rapist, known as ""The Monst...",South America,Multiple Countries,Male,1960s
682,Angel Makers of Nagyr√©v,Hungary,1911,1929,50,300,26 women who poisoned their husbands (sometime...,Europe,Hungary,Female,1910s
625,Niels H√∂gel,Germany,1999,2005,85,300,Nurse who was sentenced to life imprisonment f...,Europe,Germany,Male,1990s
9,Abul Djabar,Afghanistan,<NA>,1970,65,300,Killed 65 men and boys by strangling them with...,Asia,Afghanistan,Male,<NA>s
654,Frans Hooijmaijers,Netherlands,1970,1975,5,259,Nurse who was convicted for killing five patie...,Europe,Netherlands,Female,1970s
623,Harold Shipman,United Kingdom,1975,1998,218,250,Convicted of 15 murders and found to be respon...,Europe,United Kingdom,Male,1970s
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992,1999,193,247,"Child-murderer, torture-killer, and rapist kno...",South America,Multiple Countries,Male,1990s
627,Kermit Gosnell,United States,<NA>,2010,48,200,Kermit Gosnell is an American serial-killer an...,North America,United States,Male,<NA>s
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974,1986,72,180,"Child and woman murderer, believed to have pos...",South America,Multiple Countries,Male,1970s
39,Mariam Soulakiotis,Greece,1939,1951,27,177,"Known as ""Mother Rasputin""; abbess believed to...",Europe,Greece,Female,1930s
490,Richard Kuklinski,United States,1948,1986,3,175,NaN,North America,United States,Male,1940s

In [29]:
top15["Name"]# Tenemos un problema con Steven Massof, era un trabajador de la cl√≠nica que testific√≥ y fu√© declarado culpable 
            #  pero la mente criminal y la cl√≠nica de abortos pertenec√≠a a Kermit Gosnell.

675              Murder Incorporated
737                 The Skin Hunters
631                   Charles Cullen
756    Amelia Sach and Annie Walters
1                        Pedro L√≥pez
682          Angel Makers of Nagyr√©v
625                      Niels H√∂gel
9                        Abul Djabar
654               Frans Hooijmaijers
623                   Harold Shipman
0                      Luis Garavito
627                   Kermit Gosnell
4             Daniel Camargo Barbosa
39                Mariam Soulakiotis
490                Richard Kuklinski
Name: Name, dtype: object

In [30]:
imagenes = {
    'Murder Incorporated': 'https://www.legendsofamerica.com/wp-content/uploads/2017/08/Murderinc.jpg',
    'The Skin Hunters': 'https://static.wikia.nocookie.net/skdb/images/2/2c/Andrzej_Nowocie%C5%84.jpg/revision/latest?cb=20230707162353',
    'Charles Cullen': 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/msnbc/Components/Photos/060319/060319_cullen_vsml_8a.jpg',
    'Amelia Sach and Annie Walters': 'https://pm1.aminoapps.com/6044/e102b3c5568cd78a3fb4e16d3d4d4f032f526a8b_00.jpg',
    'Pedro L√≥pez': 'https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2018/11/14100939/Pedro-Alonso-Lopez-el-Monstruo-de-los-Andes-3.jpg',
    'Angel Makers of Nagyr√©v': 'https://www.economist.com/cdn-cgi/image/width=1424,quality=80,format=auto/content-assets/images/20230318_CUP001.jpg',
    'Niels H√∂gel': 'https://www.lavanguardia.com/files/content_image_mobile_filter/uploads/2022/04/21/6261a4bb37515.jpeg',
    'Abul Djabar': 'https://alpha-assets.tadevel-cdn.com/663d766925bc4c6ee7e00f81/720.webp',
    'Frans Hooijmaijers': 'https://thumbor.pijper.io/5EwhMNHH-OViNv253yb-ej8DMuY=/728x0/https%3A%2F%2Fcdn.pijper.io%2F2024%2F11%2Fq6DZBqjmCkIjDH1731685697.png',
    'Harold Shipman': 'https://m.media-amazon.com/images/S/pv-target-images/43d413170f9c3edaac3eceefaedc067b210f7cd44f5566140bceeb13ac977637.jpg',
    'Luis Garavito': 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Luis_Alfredo_Garavito_Cubillos.jpg',
    'Kermit Gosnell': 'https://media.philly.com/images/20140213_dn_0n0wr3al.jpg',
    'Daniel Camargo Barbosa': 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Daniel_Camargo_Barbosa_1958_Mugshot.png',
    'Mariam Soulakiotis': 'https://images.findagrave.com/photos/2024/251/245406222_a2b9c415-c479-410f-afd9-71f5b42a883a.jpeg',
    'Richard Kuklinski': 'https://swashvillage.org/storage/img/images/richard-the-iceman-kuklinski-biography_2.jpg'
}

In [31]:
top15['Image'] = top15['Name'].map(imagenes)

In [32]:
top15

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,Continent,Country Sorted,Killer Type,Decade,Image
675,Murder Incorporated,United States,1920,<NA>,400,1000,Murder Incorporated or Murder Inc. for short w...,North America,United States,Gang,1920s,https://www.legendsofamerica.com/wp-content/up...
737,The Skin Hunters,Poland,<NA>,2002,5,620,Hospital crew that killed patients in order to...,Europe,Poland,Gang,<NA>s,https://static.wikia.nocookie.net/skdb/images/...
631,Charles Cullen,United States,1988,2003,29,400,Nurse in New Jersey and Pennsylvania who murde...,North America,United States,Male,1980s,https://media-cldnry.s-nbcnews.com/image/uploa...
756,Amelia Sach and Annie Walters,United Kingdom,1900,1903,1,300,"Sach and Walters, known as the ""Finchley baby ...",Europe,United Kingdom,Female,1900s,https://pm1.aminoapps.com/6044/e102b3c5568cd78...
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969,1980,110,300,"Child-murderer and rapist, known as ""The Monst...",South America,Multiple Countries,Male,1960s,https://s3.amazonaws.com/arc-wordpress-client-...
682,Angel Makers of Nagyr√©v,Hungary,1911,1929,50,300,26 women who poisoned their husbands (sometime...,Europe,Hungary,Female,1910s,https://www.economist.com/cdn-cgi/image/width=...
625,Niels H√∂gel,Germany,1999,2005,85,300,Nurse who was sentenced to life imprisonment f...,Europe,Germany,Male,1990s,https://www.lavanguardia.com/files/content_ima...
9,Abul Djabar,Afghanistan,<NA>,1970,65,300,Killed 65 men and boys by strangling them with...,Asia,Afghanistan,Male,<NA>s,https://alpha-assets.tadevel-cdn.com/663d76692...
654,Frans Hooijmaijers,Netherlands,1970,1975,5,259,Nurse who was convicted for killing five patie...,Europe,Netherlands,Female,1970s,https://thumbor.pijper.io/5EwhMNHH-OViNv253yb-...
623,Harold Shipman,United Kingdom,1975,1998,218,250,Convicted of 15 murders and found to be respon...,Europe,United Kingdom,Male,1970s,https://m.media-amazon.com/images/S/pv-target-...
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992,1999,193,247,"Child-murderer, torture-killer, and rapist kno...",South America,Multiple Countries,Male,1990s,https://upload.wikimedia.org/wikipedia/commons...
627,Kermit Gosnell,United States,<NA>,2010,48,200,Kermit Gosnell is an American serial-killer an...,North America,United States,Male,<NA>s,https://media.philly.com/images/20140213_dn_0n...
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974,1986,72,180,"Child and woman murderer, believed to have pos...",South America,Multiple Countries,Male,1970s,https://upload.wikimedia.org/wikipedia/commons...
39,Mariam Soulakiotis,Greece,1939,1951,27,177,"Known as ""Mother Rasputin""; abbess believed to...",Europe,Greece,Female,1930s,https://images.findagrave.com/photos/2024/251/...
490,Richard Kuklinski,United States,1948,1986,3,175,NaN,North America,United States,Male,1940s,https://swashvillage.org/storage/img/images/ri...

### üïµÔ∏è‚Äç‚ôÇÔ∏èCrear columna con a√±os de actuvidad

In [24]:

# Aseguramos que Start year y End year son n√∫meros
df_killers_byvictims['Start year'] = pd.to_numeric(df_killers_byvictims['Start year'], errors='coerce')
df_killers_byvictims['End year'] = pd.to_numeric(df_killers_byvictims['End year'], errors='coerce')



# Creamos Years Active, dejando NaN si falta Start year
df_killers_byvictims['Years Active'] = df_killers_byvictims['End year'] - df_killers_byvictims['Start year']

In [145]:
df_killers_byvictims.head()

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,Continent,Country Sorted,Years Active,Decade,Crime Type,Killer Type
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992,1999,193,247,"Child-murderer, torture-killer, and rapist kno...",South America,Multiple Countries,7,1990s,Pedophilia,Male
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969,1980,110,300,"Child-murderer and rapist, known as ""The Monst...",South America,Multiple Countries,11,1960s,Pedophilia,Male
2,Javed Iqbal,Pakistan,1998,1999,100,100,"Child-murderer and rapist, known as ""Kukri"", I...",Asia,Pakistan,1,1990s,Pedophilia,Male
3,Mikhail Popkov,Russia,1992,2010,83,86,"Serial rapist-killer nicknamed ""The Werewolf"",...",Europe,Russia,18,1990s,Rape,Male
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974,1986,72,180,"Child and woman murderer, believed to have pos...",South America,Multiple Countries,12,1970s,Rape,Male

In [ ]:
df_killers_byvictims["Years Active"].isna().sum() #nos encontramos con 34 nulos

34

In [22]:
# Asegurar que Start year es n√∫mero
df_killers_byvictims['Start year'] = pd.to_numeric(df_killers_byvictims['Start year'], errors='coerce')

# Crear la columna Decade
df_killers_byvictims['Decade'] = (df_killers_byvictims['Start year'] // 10) * 10

In [23]:
df_killers_byvictims['Decade'] = df_killers_byvictims['Decade'].astype('Int64').astype(str) + 's'

In [24]:
df_killers_byvictims.head()

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,Continent,Country Sorted,Killer Type,Decade
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992,1999,193,247,"Child-murderer, torture-killer, and rapist kno...",South America,Multiple Countries,Male,1990s
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969,1980,110,300,"Child-murderer and rapist, known as ""The Monst...",South America,Multiple Countries,Male,1960s
2,Javed Iqbal,Pakistan,1998,1999,100,100,"Child-murderer and rapist, known as ""Kukri"", I...",Asia,Pakistan,Male,1990s
3,Mikhail Popkov,Russia,1992,2010,83,86,"Serial rapist-killer nicknamed ""The Werewolf"",...",Europe,Russia,Male,1990s
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974,1986,72,180,"Child and woman murderer, believed to have pos...",South America,Multiple Countries,Male,1970s

### Columna de tipo de crimen ü™í

In [135]:
crime_keywords = {

    'Pedophilia': ['Child','child-murderer','pedophilia', 'child abuse', 'child molestation', 'child rape', 'sexual assault on children', 'sexual exploitation of children'],
    'Kidnapping': ['kidnap', 'abduction'],
    'Rape': ['rape','rapist-killer', 'sexual assault', 'molestation'],
    'Torture': ['torture', 'mutilation', 'disembowelment'],
    'Robbery': ['robbery', 'theft', 'steal'],
    'Poisoning': ['poison', 'toxins', 'overdose'],
    'Arson': ['arson', 'fire', 'burn'],
    'Necrophilia': ['necrophilia', 'corpse abuse'],
    'Cannibalism': ['canibalized','cannibalism', 'eating', 'consumed'],
    'Angel of Mercy': ['angel of mercy', 'angel of death', 'caregiver', 'nurse'],
    'Murder':["killing"]
}
def categorize_crime(notes, crime_keywords):
    if isinstance(notes, str):  # Verificar si 'notes' es un string
        for crime, keywords in crime_keywords.items():
            if any(keyword in notes.lower() for keyword in keywords):  # Convertir a min√∫sculas
                return crime
    return 'Other'

# Aplicar la funci√≥n al DataFrame
df_killers_byvictims['Crime Type'] = df_killers_byvictims['Notes'].apply(categorize_crime, crime_keywords=crime_keywords)

In [137]:
df_killers_byvictims["Crime Type"].value_counts()

Crime Type
Other             477
Rape               78
Murder             64
Poisoning          47
Kidnapping         27
Angel of Mercy     22
Torture            11
Arson              10
Robbery             8
Necrophilia         6
Cannibalism         4
Pedophilia          3
Name: count, dtype: int64

### Crear columna por G√©nero üöª

In [12]:
# Listas de clasificaci√≥n

female_killers = [
    'Marie Fik√°ƒçkov√°', 'Ivanova and Olga Tamarin', 'Gwendolyn Graham and Catherine May Wood',
    'Fel√≠citas S√°nchez Aguill√≥n', 'Delfina and Mar√≠a de Jes√∫s Gonz√°lez', 'Angel Makers of Nagyr√©v',
    'Lainz Angels of Death', 'Silvia Merez Cult', 'Amelia Sach and Annie Walters', 'Belle Gunness',
    'Aileen Wuornos', 'Dorothea Puente', 'Juana Barraza', 'Jane Toppan', 'Genene Jones',
    'Beverley Allitt', 'Enriqueta Mart√≠', 'Tillie Klimek', 'Mariane N√∂lle', 'Vickie Dawn Jackson',
    'Joan Vila', 'Linda Hazzard', 'Ann Arber Hospital Killer', 'Elizabeth Wettlaufer', 'Velma Barfield',
    'Lyda Southard', 'Shirley Winters', 'Francisca Ballesteros', 'Valery Asratyan', 'Martha Rendell',
    'Sharon Kinne', 'Leonarda Cianciulli', 'Bertha Gifford', 'Rhonda Belle Martin', 'Reta Mays',
    'Marybeth Tinning', 'Jeanne Weber', 'Marie Alexandrine Becker', 'Antoinette Scieri', 'Kristen Gilbert',
    'Sonya Caleffi', 'Kimberly Clark Saenz', 'Vera Renczi', 'Mariam Soulakiotis', 'Irina Gaidamachuk',
    'Tamara Samsonova', 'Celine Lesage', 'Elisabeth Wiese', 'Anna Marie Hahn', 'Waneta Hoyt',
    'Lucy Letby', 'Frans Hooijmaijers', 'Miyuki Ishikawa', 'Amy Archer-Gilligan', 'Aino Nykopp-Koski',
    'Elfriede Blauensteiner', 'Joanna Dennehy', 'Mary Elizabeth Wilson'
]

gangs = [
    "Raya and Sakina and their husbands", "Beasts of Satan", "Chijon Family", "The Family",
    "Ian Brady and Myra Hindley", "Ray and Faye Copeland", "The Skin Hunters", "The Hern√°ndez Brothers Sect",
    "The Ciudad Ju√°rez Rebels", "Tadeusz Grzesik and the Bureaucrats Gang", "The Manson Family cult killings",
    "National Socialist Underground", "Joshi-Abhyankar serial murderers", "Hillside Stranglers",
    "Bloody Benders", "The Cleaners", "Lainz Angels of Death", "Death Angels", "Ripper Crew",
    "An√≠sio Ferreira de Sousa and followers", "Marcelo de Jesus Silva and his death squad", "Shankill Butchers",
    "Brabant killers", "Gang of Amazons", "Murder Incorporated", "Auto Shankar's Gang", "Mailoni Brothers",
    "Briley Brothers", "David Avenda√±o Ballina and his followers", "Philadelphia poison ring"
]

couples = [
    "Michael Bear Carson and Suzan Carson", "Paul Bernardo and Karla Homolka", "Raymond Fernandez and Martha Beck",
    "David and Catherine Birnie", "James Gregory Marlow and Cynthia Coffman", "Rudolfo Infante and Anna Villeda",
    "Gerald and Charlene Gallego", "Juan Carlos Hern√°ndez and Patricia Mart√≠nez", "Fred West and Rosemary West",
    "Adolfo Constanzo and Sara Aldrete", "Ray and Faye Copeland", "Ian Brady and Myra Hindley",
    "Futoshi Matsunaga and Junko Ogata", "Long Zhimin and Yan Shuxia", "Abboud and Khajawa"
]

male_groups = [
    "Joseph and Michael Kallinger", "James Paster and Stephen McCoy", "John Duffy and David Mulcahy",
    "Loren Herzog and Wesley Shermantine", "Lawrence Bittaker and Roy Norris",
    "Artyom Alexandrovich Anoufriev and Nikita Vakhtangovich Lytkin", "David Alan Gore and Fred Waterfield",
    "Hermann Duft and Hans Wilhelm Bassenauer", "Kiss brothers and Zsolt Istv√°n Pet≈ë", "Gert van Rooyen and Joey Haarhof",
    "Johannes van Rooyen and Dumisani Makhubela", "Fa Ziying and Lao Rongzhi", "Christopher Worrell and James Miller",
    "Dale Hausner and Samuel Dieteman", "Edgar √Ålvarez Cruz and Francisco Granados", "Song Jinghua and Yan Jinguang",
    "Yevgeny Nagorny and Sergei Stavitsky", "Wolfgang Abel and Marco Furlan", "Polatbay Berdaliyev and Abduseit Ormanov",
    "Shen Changyin and Shen Changpin", "Leonard Lake and Charles Ng", "John Justin Bunting, Robert Joe Wagner and James Spyridon Vlassakis",
    "Jos√© Miculax Bux and Mariano Mac√∫ Miculax", "Vladyslav Volkovic and Volodymyr Kondratenko",
    "John Allen Muhammad and Lee Boyd Malvo", "Wang Zongfang and Wang Zongwei", "Viktor Sayenko and Igor Suprunyuk",
    "Dean Corll, David Owen Brooks and Elmer Wayne Henley", "Bian Kuang, Fu Xinyuan and Luo Lianshun",
    "Hassan Orangi and Abbas Ali Zarifian", "Peng Miaoji, Ding Yunjia and Su Xiaoping"
]

unidentified = [
    "Monster of the Mangones", "Cape Town Prostitute Killer", "El Psic√≥pata",
    "Atlanta Ripper", "Cleveland Torso Murderer", "Rainbow Maniac", "Paraquat murders",
    "Long Island serial killer", "New Bedford Highway", "Edgecombe County Serial Killer",
    "Axeman of New Orleans", "Forest City Killer", "≈Å√≥d≈∫ Gay Murderer", "The Doodler", "Bible John","Monster of Florence"
]
def classify_killer(name):
    if name in female_killers:
        return 'Female'
    elif name in gangs:
        return 'Gang'
    elif name in couples:
        return 'Couple'
    elif name in male_groups:
        return 'Male Group'
    elif name in unidentified:
        return 'Unidentified'
    else:
        return 'Male'

# Aplicamos al DataFrame
df_killers_byvictims['Killer Type'] = df_killers_byvictims['Name'].apply(classify_killer)

In [25]:
df_killers_byvictims.head()

,Name,Country,Start year,End year,Proven victims,Possible victims,Notes,Continent,Country Sorted,Killer Type,Decade
0,Luis Garavito,"Colombia, Ecuador, Venezuela",1992,1999,193,247,"Child-murderer, torture-killer, and rapist kno...",South America,Multiple Countries,Male,1990s
1,Pedro L√≥pez,"Colombia, Peru, Ecuador",1969,1980,110,300,"Child-murderer and rapist, known as ""The Monst...",South America,Multiple Countries,Male,1960s
2,Javed Iqbal,Pakistan,1998,1999,100,100,"Child-murderer and rapist, known as ""Kukri"", I...",Asia,Pakistan,Male,1990s
3,Mikhail Popkov,Russia,1992,2010,83,86,"Serial rapist-killer nicknamed ""The Werewolf"",...",Europe,Russia,Male,1990s
4,Daniel Camargo Barbosa,"Colombia, Ecuador, Brazil",1974,1986,72,180,"Child and woman murderer, believed to have pos...",South America,Multiple Countries,Male,1970s

### Guardar en archivo csv el Top 15 de asesinos en serie üìÇ

In [33]:
# Guardar el DataFrame del top 15 de asesinos en serie en un archivo CSV
top15.to_csv('top15_serial_killers_by_victims.csv', index=False)

###  Guardar en archivo csv  serial killers by victims üìÅ

In [ ]:
df_killers_byvictims.to_csv('V2-serial_killers_by_victims.csv', index=False)